/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
//teste

import connection.AeroportoCRUD;
import javax.swing.JOptionPane;
import passagens_aereas.Aeroporto;

/**
 *
 * @author lucas_nuze0yo
 */
public final class Aeroporto_Cadastro extends DefaultCadastro {

    boolean atualizacao = false;
    int registroat = 0;

    /**
     * Creates new form CadastroAeroporto
     *
     * @param parent
     * @param modal
     */
    public Aeroporto_Cadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        iniciaTela();
    }

    public Aeroporto_Cadastro(java.awt.Frame parent, boolean modal, Aeroporto aeroporto) {
        super(parent, modal);
        iniciaTela(aeroporto);
    }

    public void iniciaTela() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public void iniciaTela(Aeroporto aeroporto) {
        registroat = aeroporto.getRegistro();
        initComponents();
        this.atualizacao = true;
        setCampos(aeroporto);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public void setCampos(Aeroporto aeroporto) {
        this.jTFNome.setText(aeroporto.getNome());
        this.jCBEstado.setSelectedItem(aeroporto.getEstado());
        this.jTextFieldCidade.setText(aeroporto.getCidade());
    }

    public boolean validaAeroporto(Aeroporto aeroporto) {
        if (aeroporto.getNome().equals("") || aeroporto.getCidade().equals("")) {
            JOptionPane.showMessageDialog(null, "Os campos de Nome e Cidade devem estar preenchidos.");
            return false;
        }
        AeroportoCRUD aeroportoCRUD = new AeroportoCRUD();
        for (Aeroporto a : aeroportoCRUD.buscaNome()) {
            if (a.getNome().equals(aeroporto.getNome())) {
                JOptionPane.showMessageDialog(null,"Aeroporto já existe com esse nome.");
                return false;
            }
        }
        return true;
    }

    //Mostra em tela os dados que serão inseridos e da a opção de cancelamento e nova inserção após a atual
    public void pergunta(Aeroporto aeroporto) {
        int op;
        String titulo = "Cadastro de Aeroporto";
        String texto;

        texto = "Informações a ser cadastradas:"
                + "\nNome: " + aeroporto.getNome()
                + "\nCidade: " + aeroporto.getCidade()
                + "\nEstado: " + aeroporto.getEstado();
        if (atualizacao) {
            texto += "\n"
                    + "Você confirma a atualização?";
            titulo = "Atualização";
            op = JOptionPane.showConfirmDialog(null, texto, titulo, JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                cadastraAeroporto(aeroporto);
                this.dispose();
            }
        } else {
            texto += "\n"
                    + "\nDeseja cadastrar outro?"
                    + "\nClique em cancelar para editar os dados acima.";
            op = JOptionPane.showConfirmDialog(null, texto, titulo, JOptionPane.YES_NO_CANCEL_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                cadastraAeroporto(aeroporto);
            } else if (op == JOptionPane.NO_OPTION) {
                cadastraAeroporto(aeroporto);
                this.dispose();
            }
        }
    }

    public void cadastraAeroporto(Aeroporto aeroporto) {
        AeroportoCRUD aeroCRUD = new AeroportoCRUD();
        if (atualizacao) {
            aeroCRUD.atualizar(aeroporto);
        } else {
            aeroCRUD.inserir(aeroporto);
        }
        limpaCampos();
    }

    public void limpaCampos() {
        this.jCBEstado.setSelectedItem("AC");
        this.jTFNome.setText("");
        this.jTextFieldCidade.setText("");
    }

    public void iniciaGravacaoAeroporto() {
        Aeroporto aeroporto = criaAeroporto();
        System.out.println("Reg iniciaGravacaoAeroporto: " + aeroporto.getRegistro());
        if (validaAeroporto(aeroporto)) {
            pergunta(aeroporto);
        }
    }

    public Aeroporto criaAeroporto() {
        Aeroporto aeroporto = new Aeroporto();
        aeroporto.setRegistro(registroat);
        aeroporto.setNome(this.jTFNome.getText());
        aeroporto.setCidade(this.jTextFieldCidade.getText());
        aeroporto.setEstado(this.jCBEstado.getSelectedItem().toString());
        return aeroporto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jPanelMid = new javax.swing.JPanel();
        jPanelNome = new javax.swing.JPanel();
        jLblNome1 = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLblNome2 = new javax.swing.JLabel();
        jLblEstado = new javax.swing.JLabel();
        jCBEstado = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        jLblNome3 = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jPanelBottom = new javax.swing.JPanel();
        jBtnSalvar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setModal(true);
        setName("Cadastro de Aeroporto"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().add(jPanelTop, java.awt.BorderLayout.NORTH);

        jPanelMid.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMid.setLayout(new javax.swing.BoxLayout(jPanelMid, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelNome.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLblNome1.setForeground(new java.awt.Color(255, 0, 0));
        jLblNome1.setText("*");
        jPanelNome.add(jLblNome1);

        jLblNome.setText("Nome: ");
        jPanelNome.add(jLblNome);

        jTFNome.setMaximumSize(new java.awt.Dimension(300, 20));
        jTFNome.setMinimumSize(new java.awt.Dimension(300, 20));
        jTFNome.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanelNome.add(jTFNome);
        jPanelNome.add(jPanel2);

        jPanelMid.add(jPanelNome);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLblNome2.setForeground(new java.awt.Color(255, 0, 0));
        jLblNome2.setText("*");
        jPanel1.add(jLblNome2);

        jLblEstado.setText("Estado: ");
        jPanel1.add(jLblEstado);

        jCBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel1.add(jCBEstado);
        jPanel1.add(filler1);

        jLblNome3.setForeground(new java.awt.Color(255, 0, 0));
        jLblNome3.setText("*");
        jPanel1.add(jLblNome3);

        jLabelCidade.setText("Cidade: ");
        jPanel1.add(jLabelCidade);

        jTextFieldCidade.setMaximumSize(new java.awt.Dimension(150, 20));
        jTextFieldCidade.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextFieldCidade.setName(""); // NOI18N
        jTextFieldCidade.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel1.add(jTextFieldCidade);

        jPanelMid.add(jPanel1);

        getContentPane().add(jPanelMid, java.awt.BorderLayout.CENTER);

        jBtnSalvar.setText("Salvar");
        jBtnSalvar.setMaximumSize(new java.awt.Dimension(75, 23));
        jBtnSalvar.setMinimumSize(new java.awt.Dimension(75, 23));
        jBtnSalvar.setPreferredSize(new java.awt.Dimension(75, 23));
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });
        jPanelBottom.add(jBtnSalvar);

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jPanelBottom.add(jBtnCancelar);

        getContentPane().add(jPanelBottom, java.awt.BorderLayout.SOUTH);
        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);
        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        iniciaGravacaoAeroporto();
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Aeroporto_Cadastro cadastroAeroporto = new Aeroporto_Cadastro(null, true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JComboBox<String> jCBEstado;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLblEstado;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblNome1;
    private javax.swing.JLabel jLblNome2;
    private javax.swing.JLabel jLblNome3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelMid;
    private javax.swing.JPanel jPanelNome;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTextFieldCidade;
    // End of variables declaration//GEN-END:variables
}
