/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import connection.AviaoCRUD;
import javax.swing.table.DefaultTableModel;
import passagens_aereas.Aviao;

/**
 *
 * @author lucas
 */
public class Aviao_Tabela extends javax.swing.JDialog {

    /**
     * Creates new form TabelaAviao
     *
     * @param parent
     * @param modal
     */
    public Aviao_Tabela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        escreveTabela();
    }

    private void escreveTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTbAviao.getModel();
        AviaoCRUD aviaoCRUD = new AviaoCRUD();
        System.out.println("entrou1");
        for (Aviao a : aviaoCRUD.buscaTudo()) {
            System.out.println("entrou2");
            modelo.addRow(new Object[]{
                a.getRegistro(),
                a.getModelo(),
                a.getQtd_assentos(),
                a.getQtd_assentos_esp()
            });
        }
    }
    
    private String pegaRegistro(){
        int coluna = 0;
        int linha = this.jTbAviao.getSelectedRow();
        return (String) this.jTbAviao.getValueAt(linha, coluna);
    }
    private String pegaModelo(){
        int coluna = 1;
        int linha = this.jTbAviao.getSelectedRow();
        return (String) this.jTbAviao.getValueAt(linha, coluna);
    }
    private int pegaQtd_assentos(){
        int coluna = 2;
        int linha = this.jTbAviao.getSelectedRow();
        return (int) this.jTbAviao.getValueAt(linha, coluna);
    }
    private int pegaQtd_assentos_esp(){
        int coluna = 3;
        int linha = this.jTbAviao.getSelectedRow();
        return (int) this.jTbAviao.getValueAt(linha, coluna);
    }
    
    protected void edita(){
        Aviao aviao = new Aviao();
        aviao.setRegistro(this.pegaRegistro());
        aviao.setModelo(this.pegaModelo());
        aviao.setQtd_assentos(this.pegaQtd_assentos());
        aviao.setQtd_assentos_esp(this.pegaQtd_assentos_esp());
        this.dispose();
        Aviao_Cadastro cadastro = new Aviao_Cadastro(null, true, aviao);
        Aviao_Consulta_Atualizacao consulta_Atualizacao = new Aviao_Consulta_Atualizacao(null, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbAviao = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 300));
        jScrollPane1.setRequestFocusEnabled(false);

        jTbAviao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registro", "Modelo", "Ass. Comuns", "Ass. Esp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbAviao);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);
        getContentPane().add(jPanel3, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbAviao;
    // End of variables declaration//GEN-END:variables
}
