/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
//teste

import connection.AeroportoCRUD;
import javax.swing.JOptionPane;
import passagens_aereas.Aeroporto;

/**
 *
 * @author lucas_nuze0yo
 */
public final class CadastroAeroporto extends java.awt.Dialog {

    boolean atualizacao = false;

    /**
     * Creates new form CadastroAeroporto
     *
     * @param parent
     * @param modal
     */
    public CadastroAeroporto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public CadastroAeroporto(java.awt.Frame parent, boolean modal, Aeroporto aeroporto) {
        super(parent, modal);
        initComponents();
        this.atualizacao = true;
        setCampos(aeroporto);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public void setCampos(Aeroporto aeroporto) {
        this.jTFNome.setText(aeroporto.getNome());
        this.jCBEstado.setSelectedItem(aeroporto.getEstado());
        this.jTextFieldCidade.setText(aeroporto.getCidade());
    }

    public boolean validaAeroporto(Aeroporto aeroporto) {
        if(aeroporto.getNome().equals("")||aeroporto.getCidade().equals("")){
            System.out.println("Os campos de Nome e Cidade devem estar preenchidos.");
            return false;
        }
        AeroportoCRUD aeroportoCRUD = new AeroportoCRUD();
        for (Aeroporto a : aeroportoCRUD.buscaNome()) {
            if (a.getNome().equals(aeroporto.getNome())) {
                System.out.println("Aeroporto já existe com esse nome.");
                //frase de aeroporto já existente com esse nome
                return false;
            }
        }
        return true;
    }

    //Mostra em tela os dados que serão inseridos e da a opção de cancelamento e nova inserção após a atual
    public void perguntaCadastro(Aeroporto aeroporto) {
        int op;
        String titulo = "Cadastro de Aeroporto";
        String texto;

        texto = "Informações cadastradas:"
                + "\nNome: " + aeroporto.getNome()
                + "\nCidade: " + aeroporto.getCidade()
                + "\nEstado: " + aeroporto.getEstado()
                + "\n"
                + "\nDeseja cadastrar outro?"
                + "\nClique em cancelar para editar os dados acima.";

        op = JOptionPane.showConfirmDialog(null, texto, titulo, JOptionPane.YES_NO_CANCEL_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            cadastraAeroporto(aeroporto);
        } else if (op == JOptionPane.NO_OPTION) {
            cadastraAeroporto(aeroporto);
            this.dispose();
        }
    }

    public void cadastraAeroporto(Aeroporto aeroporto) {
        AeroportoCRUD aeroCRUD = new AeroportoCRUD();
        if (atualizacao) {
            System.out.println("ATUALIZAÇÃO AEROPORTO");
        } else {
            aeroCRUD.inserir(aeroporto);
        }
        limpaCampos();
    }

    public void limpaCampos() {
        this.jCBEstado.setSelectedItem("AC");
        this.jTFNome.setText("");
        this.jTextFieldCidade.setText("");
    }

    public void iniciaGravacaoAeroporto() {
        Aeroporto aeroporto = criaAeroporto();
        if (validaAeroporto(aeroporto)) {
            perguntaCadastro(aeroporto);
        }
    }

    public Aeroporto criaAeroporto() {
        Aeroporto aeroporto = new Aeroporto();
        aeroporto.setNome(this.jTFNome.getText());
        aeroporto.setCidade(this.jTextFieldCidade.getText());
        aeroporto.setEstado(this.jCBEstado.getSelectedItem().toString());
        return aeroporto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jPanelMid = new javax.swing.JPanel();
        jPanelNome = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLblNome = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLblEstado = new javax.swing.JLabel();
        jCBEstado = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jPanelBottom = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setModal(true);
        setName("Cadastro de Aeroporto"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        add(jPanelTop, java.awt.BorderLayout.NORTH);

        jPanelMid.setLayout(new javax.swing.BoxLayout(jPanelMid, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelNome.setLayout(new java.awt.GridBagLayout());
        jPanelNome.add(jPanel3, new java.awt.GridBagConstraints());

        jLblNome.setText("Nome: ");
        jPanelNome.add(jLblNome, new java.awt.GridBagConstraints());

        jTFNome.setMaximumSize(new java.awt.Dimension(300, 20));
        jTFNome.setMinimumSize(new java.awt.Dimension(300, 20));
        jTFNome.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanelNome.add(jTFNome, new java.awt.GridBagConstraints());
        jPanelNome.add(jPanel2, new java.awt.GridBagConstraints());

        jPanelMid.add(jPanelNome);

        jLblEstado.setText("Estado: ");
        jPanel1.add(jLblEstado);

        jCBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel1.add(jCBEstado);
        jPanel1.add(filler1);

        jLabelCidade.setText("Cidade: ");
        jPanel1.add(jLabelCidade);

        jTextFieldCidade.setMaximumSize(new java.awt.Dimension(150, 20));
        jTextFieldCidade.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextFieldCidade.setName(""); // NOI18N
        jTextFieldCidade.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel1.add(jTextFieldCidade);

        jPanelMid.add(jPanel1);

        add(jPanelMid, java.awt.BorderLayout.CENTER);

        jButtonOK.setText("OK");
        jButtonOK.setMaximumSize(new java.awt.Dimension(75, 23));
        jButtonOK.setMinimumSize(new java.awt.Dimension(75, 23));
        jButtonOK.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanelBottom.add(jButtonOK);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelBottom.add(jButtonCancelar);

        add(jPanelBottom, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        iniciaGravacaoAeroporto();
    }//GEN-LAST:event_jButtonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        CadastroAeroporto cadastroAeroporto = new CadastroAeroporto(null, true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox<String> jCBEstado;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLblEstado;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelMid;
    private javax.swing.JPanel jPanelNome;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTextFieldCidade;
    // End of variables declaration//GEN-END:variables
}
