/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import connection.AviaoCRUD;
import javax.swing.JOptionPane;
import passagens_aereas.Aviao;

/**
 *
 * @author lucas_nuze0yo
 */
public class CadastroAviao extends java.awt.Dialog {

    /**
     * Creates new form CadastroAviao
     */
    public CadastroAviao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public boolean validação(Aviao aviao) {
        //códigos de validação
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMed = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLblRegistro = new javax.swing.JLabel();
        jFTFRegistro = new javax.swing.JFormattedTextField();
        jLblModelo = new javax.swing.JLabel();
        jTFModelo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelQtdAss = new javax.swing.JLabel();
        jftfAssentosComuns = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLblAssentosEspeciais = new javax.swing.JLabel();
        jFTFAssentosEspeciais = new javax.swing.JFormattedTextField();
        jPanelBaixo = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanelMed.setLayout(new javax.swing.BoxLayout(jPanelMed, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLblRegistro.setText("Registro:");
        jPanel2.add(jLblRegistro);

        try {
            jFTFRegistro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFRegistro.setMaximumSize(new java.awt.Dimension(50, 20));
        jFTFRegistro.setMinimumSize(new java.awt.Dimension(50, 20));
        jFTFRegistro.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel2.add(jFTFRegistro);

        jLblModelo.setText("Modelo:");
        jPanel2.add(jLblModelo);

        jTFModelo.setMaximumSize(new java.awt.Dimension(150, 20));
        jTFModelo.setMinimumSize(new java.awt.Dimension(150, 20));
        jTFModelo.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel2.add(jTFModelo);

        jPanelMed.add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelQtdAss.setText("Quantidade Total de Assentos:");
        jPanel3.add(jLabelQtdAss);

        jftfAssentosComuns.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftfAssentosComuns.setMaximumSize(new java.awt.Dimension(50, 20));
        jftfAssentosComuns.setMinimumSize(new java.awt.Dimension(50, 20));
        jftfAssentosComuns.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel3.add(jftfAssentosComuns);

        jPanelMed.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLblAssentosEspeciais.setText("Quantidade de Assentos Especiais:");
        jPanel4.add(jLblAssentosEspeciais);

        jFTFAssentosEspeciais.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFTFAssentosEspeciais.setMaximumSize(new java.awt.Dimension(50, 20));
        jFTFAssentosEspeciais.setMinimumSize(new java.awt.Dimension(50, 20));
        jFTFAssentosEspeciais.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel4.add(jFTFAssentosEspeciais);

        jPanelMed.add(jPanel4);

        add(jPanelMed, java.awt.BorderLayout.CENTER);

        jButtonOK.setText("Inserir");
        jButtonOK.setMaximumSize(new java.awt.Dimension(75, 23));
        jButtonOK.setMinimumSize(new java.awt.Dimension(75, 23));
        jButtonOK.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanelBaixo.add(jButtonOK);

        jButtonCancelar.setText("Cancelar");
        jPanelBaixo.add(jButtonCancelar);

        add(jPanelBaixo, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        String registro = this.jFTFRegistro.getText();
        String modelo = this.jTFModelo.getText();
        int qtd_ass_esp = Integer.parseInt(this.jFTFAssentosEspeciais.getText());
        int qtd_ass = Integer.parseInt(this.jftfAssentosComuns.getText()) - qtd_ass_esp;
        Aviao aviao = new Aviao(registro, modelo, qtd_ass, qtd_ass_esp);
        AviaoCRUD aviaocrud = new AviaoCRUD();
        if(aviaocrud.procuraRegistro(aviao.getRegistro())){
            JOptionPane.showMessageDialog(null, "Já existe um avião cadastrado com esse registro."
                    + "\nFavor informar um registro diferente.");
        }else{
            //código para armazenar o avião
        }
    }//GEN-LAST:event_jButtonOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JFormattedTextField jFTFAssentosEspeciais;
    private javax.swing.JFormattedTextField jFTFRegistro;
    private javax.swing.JLabel jLabelQtdAss;
    private javax.swing.JLabel jLblAssentosEspeciais;
    private javax.swing.JLabel jLblModelo;
    private javax.swing.JLabel jLblRegistro;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelBaixo;
    private javax.swing.JPanel jPanelMed;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JFormattedTextField jftfAssentosComuns;
    // End of variables declaration//GEN-END:variables
}
