/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import passagens_aereas.Usuario;
/**
 *
 * @author lucas_nuze0yo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio(Usuario usuario) {
        initComponents();
        //comando para deixar a janela em fullscreen
        this.setExtendedState(Inicio.MAXIMIZED_BOTH);
        //se o nível do usuário for menor que 10 a opção 2 e 3 do menu estarão inacessiveis
        if(usuario.getNivel() <= 5){
            this.menuUsuar.setEnabled(false);
        }
        if(usuario.getNivel() <= 1){
            this.menuFrota.setEnabled(false);
            this.menuAero.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        barraMenu = new javax.swing.JMenuBar();
        menuUsuar = new javax.swing.JMenu();
        menuCadastroDeUsuario = new javax.swing.JMenuItem();
        menuFrota = new javax.swing.JMenu();
        menuFrota_CadAviao = new javax.swing.JMenuItem();
        menuFrota_CadRotas = new javax.swing.JMenuItem();
        menuAero = new javax.swing.JMenu();
        menuAero_CadAero = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        menuUsuar.setText("Usuários");

        menuCadastroDeUsuario.setText("Cadastro de Usuários");
        menuCadastroDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroDeUsuarioActionPerformed(evt);
            }
        });
        menuUsuar.add(menuCadastroDeUsuario);

        barraMenu.add(menuUsuar);

        menuFrota.setText("Frota");

        menuFrota_CadAviao.setText("Cadastro de Aviões");
        menuFrota_CadAviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFrota_CadAviaoActionPerformed(evt);
            }
        });
        menuFrota.add(menuFrota_CadAviao);

        menuFrota_CadRotas.setText("Cadastro de Rotas");
        menuFrota_CadRotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFrota_CadRotasActionPerformed(evt);
            }
        });
        menuFrota.add(menuFrota_CadRotas);

        barraMenu.add(menuFrota);

        menuAero.setText("Aeroportos");

        menuAero_CadAero.setText("Cadastro de Aeroportos");
        menuAero_CadAero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAero_CadAeroActionPerformed(evt);
            }
        });
        menuAero.add(menuAero_CadAero);

        barraMenu.add(menuAero);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAero_CadAeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAero_CadAeroActionPerformed
        //inicia o cadastro de um aeroporto
        CadastroAeroporto cadAero = new CadastroAeroporto(this, true);
    }//GEN-LAST:event_menuAero_CadAeroActionPerformed

    private void menuFrota_CadAviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFrota_CadAviaoActionPerformed
        CadastroAviao cadastroAviao = new CadastroAviao(null, true);
    }//GEN-LAST:event_menuFrota_CadAviaoActionPerformed

    private void menuCadastroDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroDeUsuarioActionPerformed
        CadastroUsuario cadastroUsuario = new CadastroUsuario(null, true);
    }//GEN-LAST:event_menuCadastroDeUsuarioActionPerformed

    private void menuFrota_CadRotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFrota_CadRotasActionPerformed
        CadastroRota cadastroRota = new CadastroRota(null, true);
    }//GEN-LAST:event_menuFrota_CadRotasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenu menuAero;
    private javax.swing.JMenuItem menuAero_CadAero;
    private javax.swing.JMenuItem menuCadastroDeUsuario;
    private javax.swing.JMenu menuFrota;
    private javax.swing.JMenuItem menuFrota_CadAviao;
    private javax.swing.JMenuItem menuFrota_CadRotas;
    private javax.swing.JMenu menuUsuar;
    // End of variables declaration//GEN-END:variables
}
