/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import connection.PassagemCRUD;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import passagens_aereas.Passagem;

/**
 *
 * @author lucas
 */
public class Passagem_Tabela extends javax.swing.JDialog {

    /**
     * Creates new form TabelaPassagem
     *
     * @param parent
     * @param modal
     */
    private int pegaId() {
        int coluna = 0;
        int linha = this.jTbPassagem.getSelectedRow();
        return (int) this.jTbPassagem.getValueAt(linha, coluna);
    }

    public Passagem_Tabela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        escreveTabela();
    }

    private void escreveTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTbPassagem.getModel();
        PassagemCRUD passCRUD = new PassagemCRUD();
        for (Passagem p : passCRUD.buscaTudo()) {
            modelo.addRow(new Object[]{
                p.getId_passagem(),
                p.getNome(),
                p.getCpf(),
                p.getRg(),
                p.getData(),
                p.getHora(),
                p.getPlataforma(),
                p.getOrigem(),
                p.getDestino(),
                p.getValor(),
                p.getTipo()
            });
        }
    }

    public String pegaNome() {
        int coluna = 1;
        int linha = this.jTbPassagem.getSelectedRow();
        return (String) this.jTbPassagem.getValueAt(linha, coluna);
    }

    public String pegaCPF() {
        int coluna = 2;
        int linha = this.jTbPassagem.getSelectedRow();
        return (String) this.jTbPassagem.getValueAt(linha, coluna);
    }

    public String pegaRG() {
        int coluna = 3;
        int linha = this.jTbPassagem.getSelectedRow();
        return (String) this.jTbPassagem.getValueAt(linha, coluna);
    }

    public Date pegaData() {
        int coluna = 4;
        int linha = this.jTbPassagem.getSelectedRow();
        return (Date) this.jTbPassagem.getValueAt(linha, coluna);
    }

    public String pegaHora() {
        int coluna = 5;
        int linha = this.jTbPassagem.getSelectedRow();
        return (String) this.jTbPassagem.getValueAt(linha, coluna);
    }

    public String pegaPlataforma() {
        int coluna = 6;
        int linha = this.jTbPassagem.getSelectedRow();
        return (String) this.jTbPassagem.getValueAt(linha, coluna);
    }

    public String pegaOrigem() {
        int coluna = 7;
        int linha = this.jTbPassagem.getSelectedRow();
        return (String) this.jTbPassagem.getValueAt(linha, coluna);
    }

    public String pegaDestino() {
        int coluna = 8;
        int linha = this.jTbPassagem.getSelectedRow();
        return (String) this.jTbPassagem.getValueAt(linha, coluna);
    }
    
    public float pegaValor(){
        int coluna = 9;
        int linha = this.jTbPassagem.getSelectedRow();
        return (float) this.jTbPassagem.getValueAt(linha, coluna);
    }
    public String pegaTipo() {
        int coluna = 10;
        int linha = this.jTbPassagem.getSelectedRow();
        return (String) this.jTbPassagem.getValueAt(linha, coluna);
    }

    protected void edita() {
        Passagem passagem = new Passagem();
        passagem.setId_passagem(pegaId());
        passagem.setNome(pegaNome());
        passagem.setCpf(pegaCPF());
        passagem.setRg(pegaRG());
        passagem.setData(pegaData());
        passagem.setHora(pegaHora());
        passagem.setPlataforma(pegaPlataforma());
        passagem.setOrigem(pegaOrigem());
        passagem.setDestino(pegaDestino());
        passagem.setTipo(pegaTipo());
        passagem.setValor(pegaValor());
        this.dispose();
        Passagem_Venda venda = new Passagem_Venda(null, true, passagem);
        Passagem_Consulta_Atualizacao consulta_Atualizacao = new Passagem_Consulta_Atualizacao(null, true);
    }

    protected void exclui() {
        PassagemCRUD passagemCRUD = new PassagemCRUD();
        String texto = "Deseja realmente excluir esse item?";
        String titulo = "Exclusão";
        this.dispose();
        int op = JOptionPane.showConfirmDialog(null, texto, titulo, JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            passagemCRUD.exclusao(this.pegaId());
        }
        Passagem_Exclusao exclusao = new Passagem_Exclusao(null, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbPassagem = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 300));

        jTbPassagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "RG", "Data", "Hora", "Plataforma", "Origem", "Destino", "Valor", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(jTbPassagem);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);
        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbPassagem;
    // End of variables declaration//GEN-END:variables
}
