/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import connection.PassagemCRUD;
import javax.swing.table.DefaultTableModel;
import passagens_aereas.Passagem;

/**
 *
 * @author lucas
 */
public class Passagem_Tabela extends javax.swing.JDialog {

    /**
     * Creates new form TabelaPassagem
     * @param parent
     * @param modal
     */
    public Passagem_Tabela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        escreveTabela();
    }
    
    private void escreveTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        PassagemCRUD passCRUD = new PassagemCRUD();
        for (Passagem p : passCRUD.buscaTudo()) {
            modelo.addRow(new Object[]{
                p.getId_passagem(),
                p.getNome(),
                p.getCpf(),
                p.getRg(),
                p.getData(),
                p.getHora(),
                p.getPlataforma(),
                p.getOrigem(),
                p.getDestino(),
                p.getValor(),
                p.getTipo()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 300));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "RG", "Data", "Hora", "Plataforma", "Origem", "Destino", "Valor", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);
        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
