/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author lucas_nuze0yo
 */
public class TelaSelecAviao extends java.awt.Dialog {

    /**
     * Creates new form TelaSelecAviao
     */
    public TelaSelecAviao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBaixo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPCima = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPDir = new javax.swing.JPanel();
        jPEsq = new javax.swing.JPanel();
        jPCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jButton1.setText("Selecionar");
        jPBaixo.add(jButton1);

        jButton2.setText("Cancelar");
        jPBaixo.add(jButton2);

        add(jPBaixo, java.awt.BorderLayout.SOUTH);

        jLabel1.setText("Clique em um avião na tabela e após isso clique em selecionar.");
        jPCima.add(jLabel1);

        add(jPCima, java.awt.BorderLayout.NORTH);
        add(jPDir, java.awt.BorderLayout.EAST);
        add(jPEsq, java.awt.BorderLayout.WEST);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registro", "Modelo", "Acentos Totais", "Assentos Especiais"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPCentro.add(jScrollPane1);

        add(jPCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaSelecAviao dialog = new TelaSelecAviao(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPBaixo;
    private javax.swing.JPanel jPCentro;
    private javax.swing.JPanel jPCima;
    private javax.swing.JPanel jPDir;
    private javax.swing.JPanel jPEsq;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
