/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import connection.VooCRUD;
import java.sql.Date;
import java.sql.Time;
import javax.swing.table.DefaultTableModel;
import passagens_aereas.Voo;

/**
 *
 * @author lucas
 */
public class TelaSelecVoo extends javax.swing.JDialog {

    private int codigo;
    private String Origem;
    private String Destino;
    private String plataforma;
    private float preco_c;
    private float preco_e;
    private Date data;
    private String hora;

    public int pegaCodigo() {
        int coluna = 0;
        int linha = jTable1.getSelectedRow();
        return (int) jTable1.getValueAt(linha, coluna);
    }

    public String pegaOrigem() {
        int coluna = 1;
        int linha = jTable1.getSelectedRow();
        return (String) jTable1.getValueAt(linha, coluna);
    }

    public String pegaDestino() {
        int coluna = 2;
        int linha = jTable1.getSelectedRow();
        return (String) jTable1.getValueAt(linha, coluna);
    }

    public float pegaPc() {
        int coluna = 3;
        int linha = jTable1.getSelectedRow();
        return (float) jTable1.getValueAt(linha, coluna);
    }

    public float pegaPe() {
        int coluna = 4;
        int linha = jTable1.getSelectedRow();
        return (float) jTable1.getValueAt(linha, coluna);
    }

    public Date pegaData() {
        int coluna = 5;
        int linha = jTable1.getSelectedRow();
        return (Date) jTable1.getValueAt(linha, coluna);
    }

    public String pegaHora() {
        int coluna = 6;
        int linha = jTable1.getSelectedRow();
        return (String) jTable1.getValueAt(linha, coluna);
    }

    public TelaSelecVoo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        populaTabela();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    private void populaTabela() {
        VooCRUD vcrud = new VooCRUD();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        for (Voo v : vcrud.buscaTudo()) {
            this.setPlataforma("P" + v.getAviao());
            modelo.addRow(new Object[]{
                v.getId(),
                v.getOrigem(),
                v.getDestino(),
                v.getPreco_c(),
                v.getPreco_e(),
                v.getData(),
                v.getHora() + ":00"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBtnSelecionar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jBtnSelecionar.setText("Selecionar");
        jBtnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelecionarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnSelecionar);

        jBtnCancelar.setText("Cancelar");
        jPanel2.add(jBtnCancelar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);
        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 300));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Origem", "Destino", "Preço Comum", "Preço Especial", "Data", "Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelecionarActionPerformed
        try {
            this.setCodigo(pegaCodigo());
            this.setOrigem(pegaOrigem());
            this.setDestino(pegaDestino());
            this.setPreco_c(pegaPc());
            this.setPreco_e(pegaPe());
            this.setData(pegaData());
            this.setHora(pegaHora());
            this.setVisible(false);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jBtnSelecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        TelaSelecVoo selecVoo = new TelaSelecVoo(null, true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnSelecionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the codigo
     */
    public int getCodigo() {
        return codigo;
    }

    /**
     * @param codigo the codigo to set
     */
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    /**
     * @return the Origem
     */
    public String getOrigem() {
        return Origem;
    }

    /**
     * @param Origem the Origem to set
     */
    public void setOrigem(String Origem) {
        this.Origem = Origem;
    }

    /**
     * @return the Destino
     */
    public String getDestino() {
        return Destino;
    }

    /**
     * @param Destino the Destino to set
     */
    public void setDestino(String Destino) {
        this.Destino = Destino;
    }

    /**
     * @return the preco_c
     */
    public float getPreco_c() {
        return preco_c;
    }

    /**
     * @param preco_c the preco_c to set
     */
    public void setPreco_c(float preco_c) {
        this.preco_c = preco_c;
    }

    /**
     * @return the preco_e
     */
    public float getPreco_e() {
        return preco_e;
    }

    /**
     * @param preco_e the preco_e to set
     */
    public void setPreco_e(float preco_e) {
        this.preco_e = preco_e;
    }

    /**
     * @return the plataforma
     */
    public String getPlataforma() {
        return plataforma;
    }

    /**
     * @param plataforma the plataforma to set
     */
    public void setPlataforma(String plataforma) {
        this.plataforma = plataforma;
    }

    /**
     * @return the data
     */
    public Date getData() {
        return data;
    }

    /**
     * @param data the data to set
     */
    public void setData(Date data) {
        this.data = data;
    }

    /**
     * @return the hora
     */
    public String getHora() {
        return hora;
    }

    /**
     * @param hora the hora to set
     */
    public void setHora(String hora) {
        this.hora = hora;
    }
}
