/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import connection.UsuarioCRUD;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import passagens_aereas.Usuario;

/**
 *
 * @author lucas
 */
public class Usuario_Tabela extends javax.swing.JDialog {

    /**
     * Creates new form Usuario_Tabela
     */
    public Usuario_Tabela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        escreveTabela();
    }
    
    public void escreveTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        UsuarioCRUD uCrud = new UsuarioCRUD();
        for (Usuario u : uCrud.buscaTodos()) {
            modelo.addRow(new Object[]{
                u.getNome(),
                u.getNivel(),
                u.getSenha()
            });
        }
    }
    private String pegaNome() {
        int coluna = 0;
        int linha = this.jTable1.getSelectedRow();
        return (String) jTable1.getValueAt(linha, coluna);
    }
    private String pegaSenha() {
        int coluna = 2;
        int linha = this.jTable1.getSelectedRow();
        return (String) jTable1.getValueAt(linha, coluna);
    }
    private int pegaNivel() {
        int coluna = 1;
        int linha = this.jTable1.getSelectedRow();
        return (int) jTable1.getValueAt(linha, coluna);
    }
    
    protected void exclui() {
        String nome = pegaNome();
        this.dispose();
        int op = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o usuário "
                + nome
                + "?", "Excluir", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.OK_OPTION) {
            UsuarioCRUD usuarioCRUD = new UsuarioCRUD();
            usuarioCRUD.excluir(nome);
        }
        Usuario_Exclusao exclusao = new Usuario_Exclusao(null, true);
    }
    
    protected void edita(){
        Usuario usuario = new Usuario();
        usuario.setNome(pegaNome());
        usuario.setSenha(pegaSenha());
        usuario.setNivel(pegaNivel());
        this.dispose();
        Usuario_Cadastro cadastro = new Usuario_Cadastro(null, true, usuario);
        Usuario_Consulta_Atualizacao consulta_Atualizacao = new Usuario_Consulta_Atualizacao(null, true);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Nivel", "Senha"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
