/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import connection.VooCRUD;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import passagens_aereas.Voo;

/**
 *
 * @author lucas
 */
public class Voo_Tabela extends DefaultTabelas {

    /**
     * Creates new form TabelaVoo
     *
     * @param parent
     * @param modal
     */
    public Voo_Tabela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        escreveTabela();
    }

    private int pegaId() {
        int coluna = 0;
        int linha = this.jTbVoo.getSelectedRow();
        return (int) this.jTbVoo.getValueAt(linha, coluna);
    }

    private void escreveTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTbVoo.getModel();
        VooCRUD vooCRUD = new VooCRUD();
        for (Voo v : vooCRUD.buscaTudo()) {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getRota(),
                v.getOrigem(),
                v.getDestino(),
                v.getPreco_c(),
                v.getPreco_e(),
                v.getData(),
                v.getHora(),
                v.getAviao(),
                v.getAss_c(),
                v.getAss_e()
            });
        }
    }

    protected void exclui() {
        VooCRUD vooCRUD = new VooCRUD();
        String texto = "Deseja realmente excluir esse item?";
        String titulo = "Exclusão";
        this.dispose();
        int op = JOptionPane.showConfirmDialog(null, texto, titulo, JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            vooCRUD.exclusao(this.pegaId());
        }
        Voo_Exclusao exclusao = new Voo_Exclusao(null, true);
    }

    private int pegaHora() {
        int coluna = 7;
        int linha = this.jTbVoo.getSelectedRow();
        String valor = (String) jTbVoo.getValueAt(linha, coluna);
        String hora = valor.substring(0, 2);
        return Integer.parseInt(hora);
    }

    private int pegaMinuto() {
        int coluna = 7;
        int linha = this.jTbVoo.getSelectedRow();
        String valor = (String) jTbVoo.getValueAt(linha, coluna);
        String hora = valor.substring(3, 5);
        return Integer.parseInt(hora);
    }

    private int pegaRota() {
        int coluna = 1;
        int linha = this.jTbVoo.getSelectedRow();
        return (int) this.jTbVoo.getValueAt(linha, coluna);
    }
    
    private String pegaOrigem(){
        int coluna = 2;
        int linha = this.jTbVoo.getSelectedRow();
        return (String) this.jTbVoo.getValueAt(linha, coluna);
    }
    
    private String pegaDestino(){
        int coluna = 3;
        int linha = this.jTbVoo.getSelectedRow();
        return (String) this.jTbVoo.getValueAt(linha, coluna);
    }
    
    private float pegaPrecoC(){
        int coluna = 4;
        int linha = this.jTbVoo.getSelectedRow();
        return (float) this.jTbVoo.getValueAt(linha, coluna);
    }
    
    private float pegaPrecoE(){
        int coluna = 5;
        int linha = this.jTbVoo.getSelectedRow();
        return (float) this.jTbVoo.getValueAt(linha, coluna);
    }
    
    private Date pegaData(){
        int coluna = 6;
        int linha = this.jTbVoo.getSelectedRow();
        return (Date) this.jTbVoo.getValueAt(linha, coluna);
    }
    
    private String pegaAviao(){
        int coluna = 8;
        int linha = this.jTbVoo.getSelectedRow();
        return (String) this.jTbVoo.getValueAt(linha, coluna);
    }
    
    private int pegaQAC() {
        int coluna = 9;
        int linha = this.jTbVoo.getSelectedRow();
        return (int) this.jTbVoo.getValueAt(linha, coluna);
    }
    
    private int pegaQAE() {
        int coluna = 10;
        int linha = this.jTbVoo.getSelectedRow();
        return (int) this.jTbVoo.getValueAt(linha, coluna);
    }

    protected void edita() {
        Voo voo = new Voo();
        voo.setId(pegaId());
        voo.setRota(pegaRota());
        voo.setOrigem(pegaOrigem());
        voo.setDestino(pegaDestino());
        voo.setPreco_c(pegaPrecoC());
        voo.setPreco_e(pegaPrecoE());
        voo.setAviao(pegaAviao());
        voo.setAss_c(pegaQAC());
        voo.setAss_e(pegaQAE());
        voo.setData((java.sql.Date) pegaData());
        Voo_Cadastro cadastro = new Voo_Cadastro(null, true, voo, pegaHora(), pegaMinuto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbVoo = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 300));

        jTbVoo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Rota", "Origem", "Destino", "Preço Comum", "Preço Especial", "Data", "Hora", "Aviao", "Quantidade de Ass. Comuns ", "Quantidade de Ass. Especiais"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbVoo);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);
        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbVoo;
    // End of variables declaration//GEN-END:variables
}
