-- MySQL Script generated by MySQL Workbench
-- Sat Jun 16 01:11:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_unicorn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_unicorn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_unicorn` DEFAULT CHARACTER SET utf8 ;
USE `db_unicorn` ;

-- -----------------------------------------------------
-- Table `db_unicorn`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_unicorn`.`USUARIO` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NOT NULL,
  `SENHA` VARCHAR(50) NOT NULL,
  `NIVEL` INT NOT NULL,
  PRIMARY KEY (`ID_USUARIO`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
